/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-26 08:35:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import doa.ComplainDOA;
import model.Complain;
import model.Admin;
import doa.UserDOA;
import model.User;
import java.util.List;
import model.Admin;

public final class admin_002dhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1715143674293L));
    _jspx_dependants.put("/admin-header.jsp", Long.valueOf(1716703210377L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("doa.UserDOA");
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("doa.ComplainDOA");
    _jspx_imports_classes.add("model.Complain");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Minimalista - New Amazing HTML5 Template</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsee.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/lightcase.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("<!-- CUSTOM STYLE -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/template-style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Work+Sans:100,400,600,900&subset=latin-ext\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Admin header</title>\r\n");
      out.write("<style>\r\n");
      out.write(".abc {\r\n");
      out.write("	position: top 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"size-1140\">\r\n");
      out.write("	");

	Admin a = null;

	if (session.getAttribute("data") != null) {
		a = (Admin) session.getAttribute("data");
	} else {
		response.sendRedirect("admin-login.jsp");
	}
	
      out.write("\r\n");
      out.write("	<!-- HEADER -->\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("		<header role=\"banner\"\r\n");
      out.write("			class=\" margin-top-30 margin-m-top-0 margin-s-top-0\">\r\n");
      out.write("			<!-- Top Navigation -->\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"background-transparent background-transparent-hightlight full-width sticky\">\r\n");
      out.write("				<div class=\"s-12 l-2\">\r\n");
      out.write("					<a href=\"admin-home.jsp\" class=\"logo\"> <!-- Logo version before sticky nav -->\r\n");
      out.write("						<img class=\"logo-before\" src=\"img/e-society.png\" alt=\"img\">\r\n");
      out.write("						<!-- Logo version after sticky nav --> <img class=\"logo-after\"\r\n");
      out.write("						src=\"img/e-society.png\" alt=\"\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"s-12 l-10\">\r\n");
      out.write("					<div class=\"top-nav right\">\r\n");
      out.write("						<p class=\"nav-text\"></p>\r\n");
      out.write("						<ul class=\"right chevron\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- <li><a href=\"#\"><i class=\"fa-solid fa-envelope\"></i> </a></li> -->\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"admin-home.jsp\">Home</a></li>\r\n");
      out.write("							<li><a href=\"admin-users-page.jsp\">Users</a></li>\r\n");
      out.write("							<li><a href=\"admin-complainlist.jsp\">Complains</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"dropdown\"><a href=\"#\"> ");
      out.print(a.getName());
      out.write(" <!-- <i\r\n");
      out.write("									class=\"fa-regular fa-user fa-xs\"></i> --></a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Change Password</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Another Another\r\n");
      out.write("											Another </a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a href=\"admin-logout.jsp\">Logout <i\r\n");
      out.write("									class=\"fa-solid fa-power-off fa-xs\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<!-- The Modal -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<!-- The Modal end-->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin Home</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".table{text-align: center;}\r\n");
      out.write(".modal-body {\r\n");
      out.write("	display: contents;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter {\r\n");
      out.write("	box-shadow: 2px 2px 10px #DADADA;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	padding: 20px 10px;\r\n");
      out.write("	background-color: #e5e5e5;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: .3s linear all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter:hover {\r\n");
      out.write("	box-shadow: 4px 4px 20px black;\r\n");
      out.write("	transition: .3s linear all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter.primary {\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	color: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .card-counter.danger {\r\n");
      out.write("	background-color: #ef5350;\r\n");
      out.write("	color: #FFF;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(" .card-counter.success {\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	color: #FFF;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".card-counter.info {\r\n");
      out.write("	background-color: #26c6da;\r\n");
      out.write("	color: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter i {\r\n");
      out.write("	color: white;\r\n");
      out.write("	align-items : center;\r\n");
      out.write("	font-size: 5em;\r\n");
      out.write("	opacity: 0.2;\r\n");
      out.write("	font-size: 4em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter .count-numbers {\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 35px;\r\n");
      out.write("	top: 20px;\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-counter .count-name {\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 28px;\r\n");
      out.write("	top: 65px;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("	text-transform: capitalize;\r\n");
      out.write("	opacity: 0.5;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	Admin admin = null;
	if (session.getAttribute("data") != null) {
		admin = (Admin) request.getAttribute("data");
	} else {
		response.sendRedirect("admin-login.jsp");
	}
	
      out.write("\r\n");
      out.write("	<!-- <header class=\"section background-white\">\r\n");
      out.write("		<div class=\"line text-center\">\r\n");
      out.write("			<h1\r\n");
      out.write("				class=\"text-dark text-s-size-30 text-m-size-40 text-l-size-headline text-thin text-line-height-1\">Be\r\n");
      out.write("				More with Less</h1>\r\n");
      out.write("			<p class=\"margin-bottom-0 text-size-16 text-dark\">\r\n");
      out.write("				Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse\r\n");
      out.write("				molestie consequat, vel illum dolore eu feugiat nulla facilisis.<br>\r\n");
      out.write("				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\n");
      out.write("				nonummy nibh euismod.\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header> -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				");

				List<User> msglist = UserDOA.userPendingStatus();
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card-counter primary\">\r\n");
      out.write("					<a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#myModal\"> <i\r\n");
      out.write("						class=\"fa-regular fa-comments\"></i><span class=\"count-numbers\">\r\n");
      out.write("							");

							out.print(msglist.size());
							
      out.write("\r\n");
      out.write("					</span> <span class=\"count-name\">Messages</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- The Modal -->\r\n");
      out.write("				<div class=\"modal fade \" id=\"myModal\">\r\n");
      out.write("					<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("						<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal Header -->\r\n");
      out.write("							<div class=\"modal-header\">\r\n");
      out.write("								<h4 class=\"modal-title\">Register pending Message</h4>\r\n");
      out.write("								<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal body -->\r\n");
      out.write("							<div class=\"modal-body\">\r\n");
      out.write("								<table class=\"table\">\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th scope=\"col\">Name</th>\r\n");
      out.write("											<th scope=\"col\">Email</th>\r\n");
      out.write("											<th scope=\"col\">Contact</th>\r\n");
      out.write("											<th scope=\"col\">Status</th>\r\n");
      out.write("											<th scope=\"col\">Action</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									");

									for (User u : msglist) {
									
      out.write("\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th scope=\"row\">");
      out.print(u.getFname());
      out.write(' ');
      out.print(u.getLname());
      out.write("</th>\r\n");
      out.write("											<td>");
      out.print(u.getEmail());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getContact());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getStatus());
      out.write("</td>\r\n");
      out.write("											<td><a style=\"color: DodgerBlue;\"\r\n");
      out.write("												href=\"UserController?action=changestatus&emailid=");
      out.print(u.getEmail());
      out.write("\">Confirm</a>\r\n");
      out.write("												|| <a style=\"color: red;\"\r\n");
      out.write("												href=\"UserController?action=Rejectstatus&emailid=");
      out.print(u.getEmail());
      out.write("\">Reject</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal footer -->\r\n");
      out.write("							<div class=\"modal-footer\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- The Modal end-->\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			List<User> userlist = UserDOA.allUsers();
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card-counter success\">\r\n");
      out.write("					<a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#userModal\">\r\n");
      out.write("						<i class=\"fa fa-database\"></i> <span class=\"count-numbers\">\r\n");
      out.write("							");

							out.print(userlist.size());
							
      out.write("\r\n");
      out.write("					</span> <span class=\"count-name\">Users</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- The Modal -->\r\n");
      out.write("			<div class=\"modal fade  \" id=\"userModal\">\r\n");
      out.write("				<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("					<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Modal Header -->\r\n");
      out.write("						<div class=\"modal-header\">\r\n");
      out.write("							<h4 class=\"modal-title\">Users List</h4>\r\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- Modal body -->\r\n");
      out.write("						<div class=\"modal-body\">\r\n");
      out.write("							<table class=\"table\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">Name</th>\r\n");
      out.write("										<th scope=\"col\">Email</th>\r\n");
      out.write("										<th scope=\"col\">Contact</th>\r\n");
      out.write("										<th scope=\"col\">Address</th>\r\n");
      out.write("										<th scope=\"col\">Status</th>\r\n");
      out.write("										<!-- <th scope=\"col\">Action</th> -->\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								");

								for (User u : userlist) {
								
      out.write("\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">");
      out.print(u.getFname());
      out.write(' ');
      out.print(u.getLname());
      out.write("</th>\r\n");
      out.write("										<td>");
      out.print(u.getEmail());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(u.getContact());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(u.getAddress());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(u.getStatus());
      out.write("</td>\r\n");
      out.write("										");
      out.write("\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- Modal footer -->\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("								data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- The Modal end-->\r\n");
      out.write("			\r\n");
      out.write("\r\n");
List<Complain> comlist=ComplainDOA.allComplain(); 
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card-counter success\">\r\n");
      out.write("					<a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#comModal\">\r\n");
      out.write("						<i class=\"fa-solid fa-clipboard\"></i> <span class=\"count-numbers\">\r\n");
      out.write("							");

							out.print(comlist.size());
							
      out.write("\r\n");
      out.write("					</span> <span class=\"count-name\">Complains</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- The Modal -->\r\n");
      out.write("				<div class=\"modal fade \" id=\"comModal\">\r\n");
      out.write("					<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("						<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal Header -->\r\n");
      out.write("							<div class=\"modal-header\">\r\n");
      out.write("								<h4 class=\"modal-title\">Complains list</h4>\r\n");
      out.write("								<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal body -->\r\n");
      out.write("							<div class=\"modal-body\">\r\n");
      out.write("								<table class=\"table\">\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("										    <th scope=\"col\">User ID</th>\r\n");
      out.write("											<th scope=\"col\">Name</th>\r\n");
      out.write("											<th scope=\"col\">Email</th>\r\n");
      out.write("											<th scope=\"col\">Complain</th>\r\n");
      out.write("											<th scope=\"col\">Complain Date</th>\r\n");
      out.write("											<th scope=\"col\">Complete Date</th>\r\n");
      out.write("											<th scope=\"col\">Status</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									");

									for (Complain u : comlist) {
									
      out.write("\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<tr>\r\n");
      out.write("										    <td>");
      out.print(u.getUid());
      out.write("</td>\r\n");
      out.write("											<th scope=\"row\">");
      out.print(u.getName());
      out.write("</th>\r\n");
      out.write("											<td>");
      out.print(u.getEmail());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getComplain());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getDate());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getCompletedate());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(u.getC_status());
      out.write("</td>\r\n");
      out.write("											 ");
      out.write("\r\n");
      out.write("										</tr>\r\n");
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Modal footer -->\r\n");
      out.write("							<div class=\"modal-footer\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("									data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- The Modal end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-3\">\r\n");
      out.write("				<div class=\"card-counter success\">\r\n");
      out.write("					<i class=\"fa fa-database\"></i> <span class=\"count-numbers\">6875</span>\r\n");
      out.write("					<span class=\"count-name\">Data</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<header class=\"section background-white\">\r\n");
      out.write("		<div class=\"line text-center\">\r\n");
      out.write("			<h1\r\n");
      out.write("				class=\"text-dark text-s-size-30 text-m-size-40 text-l-size-headline text-thin text-line-height-1\">Be\r\n");
      out.write("				More with Less</h1>\r\n");
      out.write("			<p class=\"margin-bottom-0 text-size-16 text-dark\">\r\n");
      out.write("				Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse\r\n");
      out.write("				molestie consequat, vel illum dolore eu feugiat nulla facilisis.<br>\r\n");
      out.write("				Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam\r\n");
      out.write("				nonummy nibh euismod.\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Minimalista - New Amazing HTML5 Template</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsee.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/lightcase.css\">\r\n");
      out.write("<!-- CUSTOM STYLE -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/template-style.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Work+Sans:100,400,600,900&subset=latin-ext\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- FOOTER -->\r\n");
      out.write("      <footer>\r\n");
      out.write("        <!-- Contact Us -->\r\n");
      out.write("        <div class=\"background-dark padding text-center footer-social\">\r\n");
      out.write("          <a class=\"margin-right-10\" target=\"_blank\" href=\"https://www.facebook.com\"><i class=\"icon-facebook_circle text-size-30\"></i> <span class=\"text-strong text-white hide-s hide-m\">FACEBOOK</span></a>\r\n");
      out.write("          <a class=\"margin-right-10\" target=\"_blank\" href=\"https://www.twitter.com\"><i class=\"icon-twitter_circle text-size-30\"></i> <span class=\"text-strong text-white hide-s hide-m\">TWITTER</span></a>\r\n");
      out.write("          <a class=\"margin-right-10\" target=\"_blank\" href=\"https://www.instagram.com\"><i class=\"icon-instagram_circle text-size-30\"></i> <span class=\"text-strong text-white hide-s hide-m\">INSTAGRAM</span></a>\r\n");
      out.write("          <a target=\"_blank\" href=\"https://www.linkedin.com\"><i class=\"icon-linked_in_circle text-size-30\"></i> <span class=\"text-strong text-white hide-s hide-m\">LINKEDIN</span></a>                                                                         \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Footer -->\r\n");
      out.write("        <section class=\"section-small-padding text-center background-dark full-width\">\r\n");
      out.write("          <div class=\"line\">\r\n");
      out.write("            <div class=\"margin\">\r\n");
      out.write("              <!-- Collumn 1 -->              \r\n");
      out.write("              <div class=\"s-12 m-12 l-4 margin-m-bottom-30\">\r\n");
      out.write("                <h3 class=\"text-size-16\">Company Address</h3>\r\n");
      out.write("                <p class=\"text-size-14\">\r\n");
      out.write("                   Responsive Street 7<br>\r\n");
      out.write("                   London - United Kingdom<br> \r\n");
      out.write("                   Europe\r\n");
      out.write("                </p>               \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Collumn 2 -->\r\n");
      out.write("              <div class=\"s-12 m-12 l-4 margin-m-bottom-30\">\r\n");
      out.write("                <h3 class=\"text-size-16\">E-mail</h3>\r\n");
      out.write("                <p class=\"text-size-14\">\r\n");
      out.write("                   contact@sampledomain.com<br>\r\n");
      out.write("                   office@sampledomain.com\r\n");
      out.write("                </p>              \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Collumn 3 -->\r\n");
      out.write("              <div class=\"s-12 m-12 l-4 \">\r\n");
      out.write("                <h3 class=\"text-size-16\">Phone Numbers</h3>\r\n");
      out.write("                <p class=\"text-size-14\">\r\n");
      out.write("                   0800 4521 800 50<br>\r\n");
      out.write("                   0450 5896 625 16<br>\r\n");
      out.write("                   0798 6546 465 15\r\n");
      out.write("                </p>             \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>  \r\n");
      out.write("        </section>\r\n");
      out.write("        <hr class=\"break margin-top-bottom-0\" style=\"border-color: rgba(0, 0, 0, 0.80);\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Bottom Footer -->\r\n");
      out.write("        <section class=\"padding background-dark full-width\">\r\n");
      out.write("          <div class=\"text-center\">\r\n");
      out.write("            <p class=\"text-size-12\">Copyright 2019, Vision Design - graphic zoo</p>\r\n");
      out.write("            <p class=\"text-size-12\">All images is purchased from Bigstock. Do not use the images in your website.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("      </footer>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/responsee.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.events.touch.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/template-scripts.js\"></script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
