/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-21 15:59:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import doa.UserDOA;
import model.User;
import java.util.List;
import model.Admin;

public final class admin_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("doa.UserDOA");
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Minimalista - New Amazing HTML5 Template</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/components.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsee.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"owl-carousel/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/lightcase.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("<!-- CUSTOM STYLE -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/template-style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Work+Sans:100,400,600,900&subset=latin-ext\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Admin header</title>\r\n");
      out.write("<style>\r\n");
      out.write(".abc {\r\n");
      out.write("	position: top 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"size-1140\">\r\n");
      out.write("	");

	Admin a = null;

	if (session.getAttribute("data") != null) {
		a = (Admin) session.getAttribute("data");
	} else {
		response.sendRedirect("admin-login.jsp");
	}
	
      out.write("\r\n");
      out.write("	<!-- HEADER -->\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("		<header role=\"banner\"\r\n");
      out.write("			class=\" margin-top-30 margin-m-top-0 margin-s-top-0\">\r\n");
      out.write("			<!-- Top Navigation -->\r\n");
      out.write("			<nav\r\n");
      out.write("				class=\"background-transparent background-transparent-hightlight full-width sticky\">\r\n");
      out.write("				<div class=\"s-12 l-2\">\r\n");
      out.write("					<a href=\"admin-home.jsp\" class=\"logo\"> <!-- Logo version before sticky nav -->\r\n");
      out.write("						<img class=\"logo-before\" src=\"img/e-society.png\" alt=\"img\">\r\n");
      out.write("						<!-- Logo version after sticky nav --> <img class=\"logo-after\"\r\n");
      out.write("						src=\"img/e-society.png\" alt=\"\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"s-12 l-10\">\r\n");
      out.write("					<div class=\"top-nav right\">\r\n");
      out.write("						<p class=\"nav-text\"></p>\r\n");
      out.write("						<ul class=\"right chevron\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- <li><a href=\"#\"><i class=\"fa-solid fa-envelope\"></i> </a></li> -->\r\n");
      out.write("							");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"admin-home.jsp\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"dropdown\"><a href=\"#\"> ");
      out.print(a.getName());
      out.write(" <!-- <i\r\n");
      out.write("									class=\"fa-regular fa-user fa-xs\"></i> --></a>\r\n");
      out.write("								<ul class=\"dropdown-menu\">\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Change Password</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("									<li><a class=\"dropdown-item\" href=\"#\">Another Another\r\n");
      out.write("											Another </a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a href=\"admin-logout.jsp\">Logout <i\r\n");
      out.write("									class=\"fa-solid fa-power-off fa-xs\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<!-- The Modal -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<!-- The Modal end-->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
