/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-22 16:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Register form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/*@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');*/\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: 'Poppins',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  background: #1abc9c;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("::selection{\r\n");
      out.write("  background: rgba(26,188,156,0.3);\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("  max-width: 440px;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("  margin: 47px auto;\r\n");
      out.write("}\r\n");
      out.write(".wrapper{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0px 4px 10px 1px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write(".wrapper .title{\r\n");
      out.write("  height: 90px;\r\n");
      out.write("  background: #16a085;\r\n");
      out.write("  border-radius: 5px 5px 0 0;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 30px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form{\r\n");
      out.write("  padding: 30px 25px 25px 25px;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .row{\r\n");
      out.write("  height: 45px;\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .row input{\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  padding-left: 60px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  border: 1px solid lightgrey;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("form .row input:focus{\r\n");
      out.write("  border-color: #16a085;\r\n");
      out.write("  box-shadow: inset 0px 0px 2px 2px rgba(26,188,156,0.25);\r\n");
      out.write("}\r\n");
      out.write("form .row input::placeholder{\r\n");
      out.write("  color: #999;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .row i{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 47px;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  background: #16a085;\r\n");
      out.write("  border: 1px solid #16a085;\r\n");
      out.write("  border-radius: 5px 0 0 5px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .pass{\r\n");
      out.write("  margin: -8px 0 20px 0;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .pass a{\r\n");
      out.write("  color: #16a085;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .pass a:hover{\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .button input{\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  padding-left: 0px;\r\n");
      out.write("  background: #16a085;\r\n");
      out.write("  border: 1px solid #16a085;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("form .button input:hover{\r\n");
      out.write("  background: #12876f;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .signup-link{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write(".wrapper form .signup-link a{\r\n");
      out.write("  color: #16a085;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("form .signup-link a:hover{\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"title\"><span>Registration Form</span></div>\r\n");
      out.write("        <form method=\"post\" action=\"Registation\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fas fa-user\"></i>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter name\" name=\"name\" id=\"name\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("             <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" id=\"email\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fas fa-lock\"></i>\r\n");
      out.write("            <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" id=\"psw\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("            <input type=\"number\" placeholder=\"Enter mobile\" name=\"mobile\" id=\"mobile\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row button\">\r\n");
      out.write("            <input type=\"submit\" value=\"Register\">\r\n");
      out.write("            <!-- <button type=\"submit\" class=\"registerbtn\">Register</button> -->\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <div class=\"signup-link\">are you member? <a href=\"login.jsp\">login now</a></div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
