/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-14 07:26:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import doa.ProductDAO;
import model.Product;
import doa.Cartdoa;
import model.cart;
import model.WishList;
import doa.WishLIstDAO;
import java.util.List;
import model.Customer;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1714543253672L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1715341279425L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("doa.WishLIstDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Customer");
    _jspx_imports_classes.add("doa.ProductDAO");
    _jspx_imports_classes.add("doa.Cartdoa");
    _jspx_imports_classes.add("model.cart");
    _jspx_imports_classes.add("model.WishList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write(".tblset {\r\n");
      out.write("	overflow-x: scroll;\r\n");
      out.write("	font: -webkit-control;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("sup {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$('#myModal').on('shown.bs.modal', function() {\r\n");
      out.write("			$('#myInput').trigger('focus');\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	Customer c = null;
	if (session.getAttribute("data") != null) {
		c = (Customer) session.getAttribute("data");
	} else {
		response.sendRedirect("login.jsp");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Header/Navigation -->\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark\"\r\n");
      out.write("		arial-label=\"Furni navigation bar\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.jsp\">Furni<span>.</span></a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarsFurni\"\r\n");
      out.write("				aria-controls=\"navbarsFurni\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarsFurni\">\r\n");
      out.write("				<ul class=\"custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("					<!-- <li><a href=\"#\">Register <i class=\"fas fa-angle-down\"></i></a>\r\n");
      out.write("										<ul class=\"submenu\">\r\n");
      out.write("											<li><a href=\"seller-registration.jsp\">As Seller</a></li>\r\n");
      out.write("											<li><a href=\"customer-registration.jsp\">As Customer</a></li>\r\n");
      out.write("										</ul></li> -->\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"shop.jsp\">Shop</a></li>\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"#\">About us</a></li>\r\n");
      out.write("					<!-- <div class=\"dropdown\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"about.html\">other</a>\r\n");
      out.write("							<div class=\"dropdown-content\">\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li style=\"margin-left: 0px;\"><a href=\"#\" style=\"text-decoration: none;\">cust-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li style=\"margin-left: 0px;\"><a href=\"#\"\r\n");
      out.write("										style=\"text-decoration: none;\">sell-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("					</div> -->\r\n");
      out.write("					<!-- <li><a class=\"nav-link\" href=\"services.html\">Services</a></li> -->\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<ul class=\"custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<li><a class=\"nav-link\" data-toggle=\"modal\"\r\n");
      out.write("						data-target=\"#exampleModal\" href=\"#\"><img\r\n");
      out.write("							src=\"images/user.svg\"></a>\r\n");
      out.write("						<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("							role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("							aria-hidden=\"true\">\r\n");
      out.write("							<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("								<div class=\"modal-content\">\r\n");
      out.write("									<div class=\"modal-header\">\r\n");
      out.write("										<h5 class=\"modal-title\" id=\"exampleModalLabel\">\r\n");
      out.write("											Welcome :\r\n");
      out.write("											");
      out.print(c.getName());
      out.write("\r\n");
      out.write("										</h5>\r\n");
      out.write("										<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("											aria-label=\"Close\">\r\n");
      out.write("											<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("										</button>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"modal-body tblset\">\r\n");
      out.write("										<table class=\"table\">\r\n");
      out.write("											<thead>\r\n");
      out.write("												<tr>\r\n");
      out.write("													<th scope=\"col\">Id</th>\r\n");
      out.write("													<th scope=\"col\">Name</th>\r\n");
      out.write("													<th scope=\"col\">Email</th>\r\n");
      out.write("													<th scope=\"col\">Contact</th>\r\n");
      out.write("													<th scope=\"col\">Address</th>\r\n");
      out.write("												</tr>\r\n");
      out.write("											</thead>\r\n");
      out.write("											<tbody>\r\n");
      out.write("												<tr>\r\n");
      out.write("													<!-- <th scope=\"row\">1</th> -->\r\n");
      out.write("													<td>");
      out.print(c.getId());
      out.write("</td>\r\n");
      out.write("													<td>");
      out.print(c.getName());
      out.write("</td>\r\n");
      out.write("													<td>");
      out.print(c.getEmail());
      out.write("</td>\r\n");
      out.write("													<td>");
      out.print(c.getContact());
      out.write("</td>\r\n");
      out.write("													<td>");
      out.print(c.getAddress());
      out.write("</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("											</tbody>\r\n");
      out.write("										</table>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"modal-footer\">\r\n");
      out.write("										<div class=\"\">\r\n");
      out.write("											<div class=\"btn btn-secondary\">\r\n");
      out.write("												<a href=\"changepassword.jsp\" style=\"text-decoration: none;\">Change\r\n");
      out.write("													password</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<form action=\"Customercontroller\" method=\"post\">\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("												data-dismiss=\"modal\">Close</button>\r\n");
      out.write("											<a href=\"update.jsp\" class=\"btn btn-primary\">Edit</a>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div></li>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					");

					List<WishList> wlist = WishLIstDAO.getWishListByCusId(c.getId());
					
      out.write("\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"wishlist.jsp\"><i class=\"fa-regular fa-heart fa-xl\" style=\"color: #ffffff;\"></i><sup>\r\n");
      out.write("								");

								out.print(wlist.size());
								
      out.write("\r\n");
      out.write("						</sup></a></li>\r\n");
      out.write("					");
List<cart> clist = Cartdoa.getCartBycustId(c.getId());
      out.write("\r\n");
      out.write("						\r\n");
      out.write("					<li><a class=\"nav-link\" href=\"cart.jsp\"><img src=\"images/cart.svg\"><sup>\r\n");
      out.write("								");

								out.print(clist.size());
								
      out.write("\r\n");
      out.write("						</sup></a></li>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- End Header/Navigation -->\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"js/tiny-slider.js\"></script>\r\n");
      out.write("	<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Cart</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Hero Section -->\r\n");
      out.write("	<div class=\"hero\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-5\">\r\n");
      out.write("					<div class=\"intro-excerpt\">\r\n");
      out.write("						<h1>Cart</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-7\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Hero Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"untree_co-section before-footer-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mb-5\">\r\n");
      out.write("				<!-- <form class=\"col-md-12\" method=\"post\"> -->\r\n");
      out.write("				<div class=\"site-blocks-table\">\r\n");
      out.write("					<table class=\"table\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th class=\"product-thumbnail\">Image</th>\r\n");
      out.write("								<th class=\"product-name\">Product</th>\r\n");
      out.write("								<th class=\"product-price\">Price</th>\r\n");
      out.write("								<th class=\"product-quantity\">Quantity</th>\r\n");
      out.write("								<th class=\"product-total\">Total</th>\r\n");
      out.write("								<th class=\"product-remove\">Remove</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						");

						List<cart> cartlist = Cartdoa.getCartBycustId(c.getId());
						
      out.write("\r\n");
      out.write("						");

						int subtotal = 0;
						
      out.write("\r\n");
      out.write("						");

						for (cart c1 : cartlist) {
						
      out.write("\r\n");
      out.write("						");

						subtotal = subtotal + c1.getTotal_price();
						
      out.write("\r\n");
      out.write("						");

						Product p = ProductDAO.GetProductById(c1.getPid());
						
      out.write("\r\n");
      out.write("						<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td class=\"product-thumbnail\"><img\r\n");
      out.write("									src=\"image/");
      out.print(c1.getPimage());
      out.write("\" alt=\"Image\" class=\"img-fluid\"\r\n");
      out.write("									height=\"200px\" width=\"200px\"></td>\r\n");
      out.write("								<td class=\"product-name\">\r\n");
      out.write("									<h2 class=\"h5 text-black\">");
      out.print(c1.getPname());
      out.write("</h2>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>");
      out.print(c1.getPprice());
      out.write("</td>\r\n");
      out.write("								<td>\r\n");
      out.write("\r\n");
      out.write("									<div\r\n");
      out.write("										class=\"input-group mb-3 d-flex align-items-center quantity-container\"\r\n");
      out.write("										style=\"max-width: 120px;\">\r\n");
      out.write("										<!-- <div class=\"input-group-prepend\">\r\n");
      out.write("												<button class=\"btn btn-outline-black decrease\" type=\"button\">&minus;</button>\r\n");
      out.write("											</div> -->\r\n");
      out.write("										<form action=\"CartController\" method=\"post\">\r\n");
      out.write("											<input type=\"hidden\" name=\"cart_id\" value=\"");
      out.print(c1.getId());
      out.write("\">\r\n");
      out.write("											<input type=\"number\" name=\"qty\" min=1\r\n");
      out.write("												class=\"form-control text-center quantity-amount\"\r\n");
      out.write("												value=\"");
      out.print(c1.getQty());
      out.write("\" placeholder=\"\"\r\n");
      out.write("												aria-label=\"Example text with button addon\"\r\n");
      out.write("												aria-describedby=\"button-addon1\"\r\n");
      out.write("												onchange=\"this.form.submit();\">\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>");
      out.print(c1.getTotal_price());
      out.write("</td>\r\n");
      out.write("								<td><a\r\n");
      out.write("									href=\"remove_product_from_cart.jsp?id=");
      out.print(c1.getId());
      out.write("\"\r\n");
      out.write("									class=\"btn btn-black btn-sm\"><i class=\"fa-solid fa-trash\" style=\"color: #f40b23;\"></i></a></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</tbody>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<div class=\"row mb-5\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"shop.jsp\" class=\"btn btn-outline-black btn-sm btn-block\">Continue\r\n");
      out.write("								Shopping</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-md-6 pl-5\">\r\n");
      out.write("					<div class=\"row justify-content-end\">\r\n");
      out.write("						<div class=\"col-md-7\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-12 text-right border-bottom mb-5\">\r\n");
      out.write("									<h3 class=\"text-black h4 text-uppercase\">Cart Totals</h3>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row mb-3\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<span class=\"text-black\">Total Price</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 text-right\">\r\n");
      out.write("									<strong class=\"text-black\">");
      out.print(subtotal);
      out.write("</strong>\r\n");
      out.write("								</div>\r\n");
      out.write("								");
cart c1= Cartdoa.getSingleCartByCusId(c.getId());
      out.write("\r\n");
      out.write("								");
if(c1 != null) {
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<form method=\"post\" action=\"payment.jsp?amount=");
      out.print(subtotal);
      out.write("&cid=");
      out.print(c1.getId());
      out.write("\">\r\n");
      out.write("								\r\n");
      out.write("								<input class=\" my-4 btn btn-outline-black btn-sm btn-block\" value=\"CheckOut\" type=\"submit\" onclick=\"\">\r\n");
      out.write("							</form>\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"bootstrap, bootstrap4\" />\r\n");
      out.write("\r\n");
      out.write("		<!-- Bootstrap CSS -->\r\n");
      out.write("		<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("		<title>Shoping</title>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Footer Section -->\r\n");
      out.write("	<footer class=\"footer-section\">\r\n");
      out.write("		<div class=\"container relative\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sofa-img\">\r\n");
      out.write("				<!-- <img src=\"images/sofa.png\" alt=\"Image\" class=\"img-fluid\"> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"subscription-form\">\r\n");
      out.write("						<h3 class=\"d-flex align-items-center\">\r\n");
      out.write("							<span class=\"me-1\"><img src=\"images/envelope-outline.svg\"\r\n");
      out.write("								alt=\"Image\" class=\"img-fluid\"></span><span>Subscribe to\r\n");
      out.write("								Newsletter</span>\r\n");
      out.write("						</h3>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"#\" class=\"row g-3\">\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your name\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your email\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button class=\"btn btn-primary\">\r\n");
      out.write("									<span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-5 mb-5\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"mb-4 footer-logo-wrap\">\r\n");
      out.write("						<a href=\"#\" class=\"footer-logo\">Furni<span>.</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"mb-4\">Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("						Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet\r\n");
      out.write("						velit. Aliquam vulputate velit imperdiet dolor tempor tristique.\r\n");
      out.write("						Pellentesque habitant</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled custom-social\">\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-facebook-f\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-twitter\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-instagram\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-linkedin\"></span></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"row links-wrap\">\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">About us</a></li>\r\n");
      out.write("								<li><a href=\"#\">Services</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Support</a></li>\r\n");
      out.write("								<li><a href=\"#\">Knowledge base</a></li>\r\n");
      out.write("								<li><a href=\"#\">Live chat</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("								<li><a href=\"#\">Our team</a></li>\r\n");
      out.write("								<li><a href=\"#\">Leadership</a></li>\r\n");
      out.write("								<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Nordic Chair</a></li>\r\n");
      out.write("								<li><a href=\"#\">Kruzo Aero</a></li>\r\n");
      out.write("								<li><a href=\"#\">Ergonomic Chair</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"border-top copyright\">\r\n");
      out.write("				<div class=\"row pt-4\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<p class=\"mb-2 text-center text-lg-start\">\r\n");
      out.write("							Copyright &copy;\r\n");
      out.write("							<script>\r\n");
      out.write("								document.write(new Date().getFullYear());\r\n");
      out.write("							</script>\r\n");
      out.write("							. All Rights Reserved. &mdash; Designed with love by <a\r\n");
      out.write("								href=\"https://untree.co\">Untree.co</a> Distributed By <a\r\n");
      out.write("								href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("							<!-- License information: https://untree.co/license/ -->\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-6 text-center text-lg-end\">\r\n");
      out.write("						<ul class=\"list-unstyled d-inline-flex ms-auto\">\r\n");
      out.write("							<li class=\"me-4\"><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer Section -->\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"js/tiny-slider.js\"></script>\r\n");
      out.write("		<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
