/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-14 08:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1714543253672L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  ");
      out.write(" \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"bootstrap, bootstrap4\" />\r\n");
      out.write("\r\n");
      out.write("		<!-- Bootstrap CSS -->\r\n");
      out.write("		<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("		<title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>\r\n");
      out.write("	</head>\r\n");
      out.write("<style>\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("	 display: none; \r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #3b5d50;\r\n");
      out.write("    min-width: max-content;/* 200px; */\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    padding: 11px ;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    /* margin-left: 0px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("	<body>\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Header/Navigation -->\r\n");
      out.write("		  <nav class=\"custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark\" arial-label=\"Furni navigation bar\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.html\">Furni<span>.</span></a>\r\n");
      out.write("\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarsFurni\" aria-controls=\"navbarsFurni\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarsFurni\">\r\n");
      out.write("					<ul class=\"custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0\">\r\n");
      out.write("						<li class=\"nav-item \">\r\n");
      out.write("							<a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"shop.jsp\">Shop</a></li> -->\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"about.html\">About us</a></li> -->\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"services.html\">Services</a></li> -->\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\">Login</a></li>\r\n");
      out.write("							<div class=\"dropdown-content\">\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"login.jsp\" style=\"text-decoration: none;\">cust-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"sell-login.jsp\" style=\"text-decoration: none;\">sell-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\">Register</a></li>\r\n");
      out.write("							<div class=\"dropdown-content\">\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"register.jsp\" style=\"text-decoration: none;\">cust-Register</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"sell-register.jsp\" style=\"text-decoration: none;\">sell-Register</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\"><img src=\"images/user.svg\"></a></li>\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\"><img src=\"images/cart.svg\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("				\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Header/Navigation -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Hero Section -->\r\n");
      out.write("			<div class=\"hero\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row justify-content-between\">\r\n");
      out.write("						<div class=\"col-lg-5\">\r\n");
      out.write("							<div class=\"intro-excerpt\">\r\n");
      out.write("								<h1>Modern Interior <span clsas=\"d-block\">Design Studio</span></h1>\r\n");
      out.write("								<p class=\"mb-4\">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>\r\n");
      out.write("								<p><a href=\"#\" class=\"btn btn-secondary me-2\">Shop Now</a><a href=\"#\" class=\"btn btn-white-outline\">Explore</a></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- <div class=\"col-lg-7\">\r\n");
      out.write("							<div class=\"hero-img-wrap\">\r\n");
      out.write("								<img src=\"images/couch.png\" class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		<!-- End Hero Section -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Product Section -->\r\n");
      out.write("		<div class=\"product-section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Start Column 1 -->\r\n");
      out.write("					<div class=\"col-md-12 col-lg-3 mb-5 mb-lg-0\">\r\n");
      out.write("						<h2 class=\"mb-4 section-title\">Crafted with excellent material.</h2>\r\n");
      out.write("						<p class=\"mb-4\">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. </p>\r\n");
      out.write("						<p><a href=\"\" class=\"btn\">Explore</a></p>\r\n");
      out.write("					</div> \r\n");
      out.write("					<!-- End Column 1 -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Start Column 2 -->\r\n");
      out.write("					<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("						<a class=\"product-item\" href=\"#\">\r\n");
      out.write("							<img src=\"images/product-1.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("							<h3 class=\"product-title\">Nordic Chair</h3>\r\n");
      out.write("							<strong class=\"product-price\">$50.00</strong>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"icon-cross\">\r\n");
      out.write("								<img src=\"images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("							</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div> \r\n");
      out.write("					<!-- End Column 2 -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Start Column 3 -->\r\n");
      out.write("					<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("						<a class=\"product-item\" href=\"#\">\r\n");
      out.write("							<img src=\"images/product-2.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("							<h3 class=\"product-title\">Kruzo Aero Chair</h3>\r\n");
      out.write("							<strong class=\"product-price\">$78.00</strong>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"icon-cross\">\r\n");
      out.write("								<img src=\"images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("							</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Column 3 -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Start Column 4 -->\r\n");
      out.write("					<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("						<a class=\"product-item\" href=\"#\">\r\n");
      out.write("							<img src=\"images/product-3.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("							<h3 class=\"product-title\">Ergonomic Chair</h3>\r\n");
      out.write("							<strong class=\"product-price\">$43.00</strong>\r\n");
      out.write("\r\n");
      out.write("							<span class=\"icon-cross\">\r\n");
      out.write("								<img src=\"images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("							</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Column 4 -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Product Section -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Why Choose Us Section -->\r\n");
      out.write("		<div class=\"why-choose-section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row justify-content-between\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<h2 class=\"section-title\">Why Choose Us</h2>\r\n");
      out.write("						<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row my-5\">\r\n");
      out.write("							<div class=\"col-6 col-md-6\">\r\n");
      out.write("								<div class=\"feature\">\r\n");
      out.write("									<div class=\"icon\">\r\n");
      out.write("										<img src=\"images/truck.svg\" alt=\"Image\" class=\"imf-fluid\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<h3>Fast &amp; Free Shipping</h3>\r\n");
      out.write("									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-6 col-md-6\">\r\n");
      out.write("								<div class=\"feature\">\r\n");
      out.write("									<div class=\"icon\">\r\n");
      out.write("										<img src=\"images/bag.svg\" alt=\"Image\" class=\"imf-fluid\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<h3>Easy to Shop</h3>\r\n");
      out.write("									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-6 col-md-6\">\r\n");
      out.write("								<div class=\"feature\">\r\n");
      out.write("									<div class=\"icon\">\r\n");
      out.write("										<img src=\"images/support.svg\" alt=\"Image\" class=\"imf-fluid\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<h3>24/7 Support</h3>\r\n");
      out.write("									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-6 col-md-6\">\r\n");
      out.write("								<div class=\"feature\">\r\n");
      out.write("									<div class=\"icon\">\r\n");
      out.write("										<img src=\"images/return.svg\" alt=\"Image\" class=\"imf-fluid\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<h3>Hassle Free Returns</h3>\r\n");
      out.write("									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-5\">\r\n");
      out.write("						<div class=\"img-wrap\">\r\n");
      out.write("							<img src=\"images/why-choose-us-img.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Why Choose Us Section -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start We Help Section -->\r\n");
      out.write("		<div class=\"we-help-section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row justify-content-between\">\r\n");
      out.write("					<div class=\"col-lg-7 mb-5 mb-lg-0\">\r\n");
      out.write("						<div class=\"imgs-grid\">\r\n");
      out.write("							<div class=\"grid grid-1\"><img src=\"images/img-grid-1.jpg\" alt=\"Untree.co\"></div>\r\n");
      out.write("							<div class=\"grid grid-2\"><img src=\"images/img-grid-2.jpg\" alt=\"Untree.co\"></div>\r\n");
      out.write("							<div class=\"grid grid-3\"><img src=\"images/img-grid-3.jpg\" alt=\"Untree.co\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-5 ps-lg-5\">\r\n");
      out.write("						<h2 class=\"section-title mb-4\">We Help You Make Modern Interior Design</h2>\r\n");
      out.write("						<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada</p>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"list-unstyled custom-list my-4\">\r\n");
      out.write("							<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("							<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("							<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("							<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<p><a herf=\"#\" class=\"btn\">Explore</a></p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End We Help Section -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Popular Product -->\r\n");
      out.write("		<div class=\"popular-product\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("						<div class=\"product-item-sm d-flex\">\r\n");
      out.write("							<div class=\"thumbnail\">\r\n");
      out.write("								<img src=\"images/product-1.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pt-3\">\r\n");
      out.write("								<h3>Nordic Chair</h3>\r\n");
      out.write("								<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio </p>\r\n");
      out.write("								<p><a href=\"#\">Read More</a></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("						<div class=\"product-item-sm d-flex\">\r\n");
      out.write("							<div class=\"thumbnail\">\r\n");
      out.write("								<img src=\"images/product-2.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pt-3\">\r\n");
      out.write("								<h3>Kruzo Aero Chair</h3>\r\n");
      out.write("								<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio </p>\r\n");
      out.write("								<p><a href=\"#\">Read More</a></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("						<div class=\"product-item-sm d-flex\">\r\n");
      out.write("							<div class=\"thumbnail\">\r\n");
      out.write("								<img src=\"images/product-3.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pt-3\">\r\n");
      out.write("								<h3>Ergonomic Chair</h3>\r\n");
      out.write("								<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio </p>\r\n");
      out.write("								<p><a href=\"#\">Read More</a></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Popular Product -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Testimonial Slider -->\r\n");
      out.write("		<div class=\"testimonial-section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-7 mx-auto text-center\">\r\n");
      out.write("						<h2 class=\"section-title\">Testimonials</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row justify-content-center\">\r\n");
      out.write("					<div class=\"col-lg-12\">\r\n");
      out.write("						<div class=\"testimonial-slider-wrap text-center\">\r\n");
      out.write("\r\n");
      out.write("							<div id=\"testimonial-nav\">\r\n");
      out.write("								<span class=\"prev\" data-controls=\"prev\"><span class=\"fa fa-chevron-left\"></span></span>\r\n");
      out.write("								<span class=\"next\" data-controls=\"next\"><span class=\"fa fa-chevron-right\"></span></span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"testimonial-slider\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"row justify-content-center\">\r\n");
      out.write("										<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("											<div class=\"testimonial-block text-center\">\r\n");
      out.write("												<blockquote class=\"mb-5\">\r\n");
      out.write("													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("												</blockquote>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"author-info\">\r\n");
      out.write("													<div class=\"author-pic\">\r\n");
      out.write("														<img src=\"images/person-1.png\" alt=\"Maria Jones\" class=\"img-fluid\">\r\n");
      out.write("													</div>\r\n");
      out.write("													<h3 class=\"font-weight-bold\">Maria Jones</h3>\r\n");
      out.write("													<span class=\"position d-block mb-3\">CEO, Co-Founder, XYZ Inc.</span>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div> \r\n");
      out.write("								<!-- END item -->\r\n");
      out.write("\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"row justify-content-center\">\r\n");
      out.write("										<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("											<div class=\"testimonial-block text-center\">\r\n");
      out.write("												<blockquote class=\"mb-5\">\r\n");
      out.write("													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("												</blockquote>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"author-info\">\r\n");
      out.write("													<div class=\"author-pic\">\r\n");
      out.write("														<img src=\"images/person-1.png\" alt=\"Maria Jones\" class=\"img-fluid\">\r\n");
      out.write("													</div>\r\n");
      out.write("													<h3 class=\"font-weight-bold\">Maria Jones</h3>\r\n");
      out.write("													<span class=\"position d-block mb-3\">CEO, Co-Founder, XYZ Inc.</span>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div> \r\n");
      out.write("								<!-- END item -->\r\n");
      out.write("\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"row justify-content-center\">\r\n");
      out.write("										<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("											<div class=\"testimonial-block text-center\">\r\n");
      out.write("												<blockquote class=\"mb-5\">\r\n");
      out.write("													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("												</blockquote>\r\n");
      out.write("\r\n");
      out.write("												<div class=\"author-info\">\r\n");
      out.write("													<div class=\"author-pic\">\r\n");
      out.write("														<img src=\"images/person-1.png\" alt=\"Maria Jones\" class=\"img-fluid\">\r\n");
      out.write("													</div>\r\n");
      out.write("													<h3 class=\"font-weight-bold\">Maria Jones</h3>\r\n");
      out.write("													<span class=\"position d-block mb-3\">CEO, Co-Founder, XYZ Inc.</span>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div> \r\n");
      out.write("								<!-- END item -->\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Testimonial Slider -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Start Blog Section -->\r\n");
      out.write("		<div class=\"blog-section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row mb-5\">\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<h2 class=\"section-title\">Recent Blog</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 text-start text-md-end\">\r\n");
      out.write("						<a href=\"#\" class=\"more\">View All Posts</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-sm-6 col-md-4 mb-4 mb-md-0\">\r\n");
      out.write("						<div class=\"post-entry\">\r\n");
      out.write("							<a href=\"#\" class=\"post-thumbnail\"><img src=\"images/post-1.jpg\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("							<div class=\"post-content-entry\">\r\n");
      out.write("								<h3><a href=\"#\">First Time Home Owner Ideas</a></h3>\r\n");
      out.write("								<div class=\"meta\">\r\n");
      out.write("									<span>by <a href=\"#\">Kristin Watson</a></span> <span>on <a href=\"#\">Dec 19, 2021</a></span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-sm-6 col-md-4 mb-4 mb-md-0\">\r\n");
      out.write("						<div class=\"post-entry\">\r\n");
      out.write("							<a href=\"#\" class=\"post-thumbnail\"><img src=\"images/post-2.jpg\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("							<div class=\"post-content-entry\">\r\n");
      out.write("								<h3><a href=\"#\">How To Keep Your Furniture Clean</a></h3>\r\n");
      out.write("								<div class=\"meta\">\r\n");
      out.write("									<span>by <a href=\"#\">Robert Fox</a></span> <span>on <a href=\"#\">Dec 15, 2021</a></span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-12 col-sm-6 col-md-4 mb-4 mb-md-0\">\r\n");
      out.write("						<div class=\"post-entry\">\r\n");
      out.write("							<a href=\"#\" class=\"post-thumbnail\"><img src=\"images/post-3.jpg\" alt=\"Image\" class=\"img-fluid\"></a>\r\n");
      out.write("							<div class=\"post-content-entry\">\r\n");
      out.write("								<h3><a href=\"#\">Small Space Furniture Apartment Ideas</a></h3>\r\n");
      out.write("								<div class=\"meta\">\r\n");
      out.write("									<span>by <a href=\"#\">Kristin Watson</a></span> <span>on <a href=\"#\">Dec 12, 2021</a></span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"bootstrap, bootstrap4\" />\r\n");
      out.write("\r\n");
      out.write("		<!-- Bootstrap CSS -->\r\n");
      out.write("		<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("		<title>Shoping</title>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Footer Section -->\r\n");
      out.write("	<footer class=\"footer-section\">\r\n");
      out.write("		<div class=\"container relative\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sofa-img\">\r\n");
      out.write("				<!-- <img src=\"images/sofa.png\" alt=\"Image\" class=\"img-fluid\"> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"subscription-form\">\r\n");
      out.write("						<h3 class=\"d-flex align-items-center\">\r\n");
      out.write("							<span class=\"me-1\"><img src=\"images/envelope-outline.svg\"\r\n");
      out.write("								alt=\"Image\" class=\"img-fluid\"></span><span>Subscribe to\r\n");
      out.write("								Newsletter</span>\r\n");
      out.write("						</h3>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"#\" class=\"row g-3\">\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your name\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your email\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button class=\"btn btn-primary\">\r\n");
      out.write("									<span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-5 mb-5\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"mb-4 footer-logo-wrap\">\r\n");
      out.write("						<a href=\"#\" class=\"footer-logo\">Furni<span>.</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"mb-4\">Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("						Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet\r\n");
      out.write("						velit. Aliquam vulputate velit imperdiet dolor tempor tristique.\r\n");
      out.write("						Pellentesque habitant</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled custom-social\">\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-facebook-f\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-twitter\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-instagram\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-linkedin\"></span></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"row links-wrap\">\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">About us</a></li>\r\n");
      out.write("								<li><a href=\"#\">Services</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Support</a></li>\r\n");
      out.write("								<li><a href=\"#\">Knowledge base</a></li>\r\n");
      out.write("								<li><a href=\"#\">Live chat</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("								<li><a href=\"#\">Our team</a></li>\r\n");
      out.write("								<li><a href=\"#\">Leadership</a></li>\r\n");
      out.write("								<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Nordic Chair</a></li>\r\n");
      out.write("								<li><a href=\"#\">Kruzo Aero</a></li>\r\n");
      out.write("								<li><a href=\"#\">Ergonomic Chair</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"border-top copyright\">\r\n");
      out.write("				<div class=\"row pt-4\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<p class=\"mb-2 text-center text-lg-start\">\r\n");
      out.write("							Copyright &copy;\r\n");
      out.write("							<script>\r\n");
      out.write("								document.write(new Date().getFullYear());\r\n");
      out.write("							</script>\r\n");
      out.write("							. All Rights Reserved. &mdash; Designed with love by <a\r\n");
      out.write("								href=\"https://untree.co\">Untree.co</a> Distributed By <a\r\n");
      out.write("								href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("							<!-- License information: https://untree.co/license/ -->\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-6 text-center text-lg-end\">\r\n");
      out.write("						<ul class=\"list-unstyled d-inline-flex ms-auto\">\r\n");
      out.write("							<li class=\"me-4\"><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer Section -->\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"js/tiny-slider.js\"></script>\r\n");
      out.write("		<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
