/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-14 04:46:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1714543253672L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Customer Register Form</title>\r\n");
      out.write("<style>\r\n");
      out.write(".btn {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-family: \"Inter\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contain {\r\n");
      out.write("	\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	height: 480px;\r\n");
      out.write("	width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".reg{margin-top: 20px;}\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("	 display: none; \r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #3b5d50;\r\n");
      out.write("    min-width: 200px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    padding: 11px ;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    /* margin-left: 0px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Start Header/Navigation -->\r\n");
      out.write("		  <nav class=\"custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark\" arial-label=\"Furni navigation bar\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.html\">Furni<span>.</span></a>\r\n");
      out.write("\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarsFurni\" aria-controls=\"navbarsFurni\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarsFurni\">\r\n");
      out.write("					<ul class=\"custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0\">\r\n");
      out.write("						<li class=\"nav-item \">\r\n");
      out.write("							<a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"shop.jsp\">Shop</a></li> -->\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"about.html\">About us</a></li> -->\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"services.html\">Services</a></li> -->\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\">Login</a></li>\r\n");
      out.write("							<div class=\"dropdown-content\">\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"login.jsp\" style=\"text-decoration: none;\">cust-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"sell-login.jsp\" style=\"text-decoration: none;\">sell-login</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"dropdown\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\">Register</a></li>\r\n");
      out.write("							<div class=\"dropdown-content\">\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"register.jsp\" style=\"text-decoration: none;\">cust-Register</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("								<ul type=\"none\">\r\n");
      out.write("									<li><a href=\"sell-register.jsp\" style=\"text-decoration: none;\">sell-Register</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<!-- <li><a class=\"nav-link\" href=\"register.jsp\">register</a></li>\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"login.jsp\">login</a></li> -->\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5\">\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"#\"><img src=\"images/user.svg\"></a></li>\r\n");
      out.write("						<li><a class=\"nav-link\" href=\"cart.html\"><img src=\"images/cart.svg\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("				\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Header/Navigation -->\r\n");
      out.write("	<form action=\"Customercontroller\" method=\"post\">\r\n");
      out.write("		<div class=\"main\">\r\n");
      out.write("			<div class=\"contain\">\r\n");
      out.write("				<div class=\"\">\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<h2 style=\"text-align: center;\"> Customer Registation</h2>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"text-black\" for=\"fname\">Name</label> <input\r\n");
      out.write("								type=\"text\" class=\"form-control\" name=\"name\" id=\"fname\"\r\n");
      out.write("								placeholder=\"Enter Your Name\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"text-black\" for=\"lname\">Email</label> <input\r\n");
      out.write("								type=\"email\" class=\"form-control\" name=\"email\" id=\"lname\"\r\n");
      out.write("								placeholder=\"Enter Your Email\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"text-black\" for=\"lname\">Contact</label> <input\r\n");
      out.write("								type=\"text\" class=\"form-control\" name=\"contact\" id=\"lname\"\r\n");
      out.write("								placeholder=\"Enter Your Contact\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"text-black\" for=\"lname\">Address</label> <input\r\n");
      out.write("								type=\"text\" class=\"form-control\" name=\"address\" id=\"lname\"\r\n");
      out.write("								placeholder=\"Enter Your Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label class=\"text-black\" for=\"lname\">Password</label> <input\r\n");
      out.write("								type=\"password\" class=\"form-control\" name=\"password\" id=\"lname\"\r\n");
      out.write("								placeholder=\"Enter Your Password\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<input type=\"submit\" class=\"btn btn-primary-hover-outline\"\r\n");
      out.write("						name=\"action\" value=\"Register\">\r\n");
      out.write("						\r\n");
      out.write("						<h4 class=\"reg\">Do You have Account? <a href=\"login.jsp\">Login</a></h4>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("  <meta name=\"keywords\" content=\"bootstrap, bootstrap4\" />\r\n");
      out.write("\r\n");
      out.write("		<!-- Bootstrap CSS -->\r\n");
      out.write("		<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("		<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("		<title>Shoping</title>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Footer Section -->\r\n");
      out.write("	<footer class=\"footer-section\">\r\n");
      out.write("		<div class=\"container relative\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sofa-img\">\r\n");
      out.write("				<!-- <img src=\"images/sofa.png\" alt=\"Image\" class=\"img-fluid\"> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"subscription-form\">\r\n");
      out.write("						<h3 class=\"d-flex align-items-center\">\r\n");
      out.write("							<span class=\"me-1\"><img src=\"images/envelope-outline.svg\"\r\n");
      out.write("								alt=\"Image\" class=\"img-fluid\"></span><span>Subscribe to\r\n");
      out.write("								Newsletter</span>\r\n");
      out.write("						</h3>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"#\" class=\"row g-3\">\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your name\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your email\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button class=\"btn btn-primary\">\r\n");
      out.write("									<span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-5 mb-5\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"mb-4 footer-logo-wrap\">\r\n");
      out.write("						<a href=\"#\" class=\"footer-logo\">Furni<span>.</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"mb-4\">Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("						Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet\r\n");
      out.write("						velit. Aliquam vulputate velit imperdiet dolor tempor tristique.\r\n");
      out.write("						Pellentesque habitant</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled custom-social\">\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-facebook-f\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-twitter\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-instagram\"></span></a></li>\r\n");
      out.write("						<li><a href=\"#\"><span class=\"fa fa-brands fa-linkedin\"></span></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"row links-wrap\">\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">About us</a></li>\r\n");
      out.write("								<li><a href=\"#\">Services</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Support</a></li>\r\n");
      out.write("								<li><a href=\"#\">Knowledge base</a></li>\r\n");
      out.write("								<li><a href=\"#\">Live chat</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("								<li><a href=\"#\">Our team</a></li>\r\n");
      out.write("								<li><a href=\"#\">Leadership</a></li>\r\n");
      out.write("								<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Nordic Chair</a></li>\r\n");
      out.write("								<li><a href=\"#\">Kruzo Aero</a></li>\r\n");
      out.write("								<li><a href=\"#\">Ergonomic Chair</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"border-top copyright\">\r\n");
      out.write("				<div class=\"row pt-4\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<p class=\"mb-2 text-center text-lg-start\">\r\n");
      out.write("							Copyright &copy;\r\n");
      out.write("							<script>\r\n");
      out.write("								document.write(new Date().getFullYear());\r\n");
      out.write("							</script>\r\n");
      out.write("							. All Rights Reserved. &mdash; Designed with love by <a\r\n");
      out.write("								href=\"https://untree.co\">Untree.co</a> Distributed By <a\r\n");
      out.write("								href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("							<!-- License information: https://untree.co/license/ -->\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-6 text-center text-lg-end\">\r\n");
      out.write("						<ul class=\"list-unstyled d-inline-flex ms-auto\">\r\n");
      out.write("							<li class=\"me-4\"><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer Section -->\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"js/tiny-slider.js\"></script>\r\n");
      out.write("		<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
